name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '16.13.0'
    - name: prepare
      run: npm install typescript source-map-support --save-dev
    - name: compilation
      run: npx tsc -p $PWD
    - name: tests
      run: chmod a+x ./test/run-tests.sh && ./test/run-tests.sh
