name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: prepare
      run: npm install typescript --save-dev
    - name: compilation
      run: npx tsc -p $PWD